language: R
sudo: no
cache: packages
env:
  global:
  - AUTHOR_EMAIL=woof
  - ENCRYPTION_LABEL=tKVh3qoFG3qm
  - AUTHOR_EMAIL=first.last@example.com
  - ENCRYPTION_LABEL=fepkGIJpNFD3
after_success:
- chmod 755 .push_gh_pages.sh
- ./.push_gh_pages.sh

