language: R
sudo: no
cache: packages
env:
  global:
  - AUTHOR_EMAIL=first.last@example.com
  - ENCRYPTION_LABEL=FWmQba3dYsw9
after_success:
- chmod 755 .push_gh_pages.sh
- ./.push_gh_pages.sh
- chmod 755 .push_gh_pages.sh
- ./.push_gh_pages.sh
- chmod 755 .push_gh_pages.sh
- ./.push_gh_pages.sh

