language: R
sudo: no
cache: packages
env:
  global:
  - AUTHOR_EMAIL=mika.br@gmail.com
  - ENCRYPTION_LABEL=wGrBOa7eqbN3
  - AUTHOR_EMAIL=mika.br@gmail.com
  - ENCRYPTION_LABEL=rZIo6VyBNhqX
  - AUTHOR_EMAIL=mika.br@gmail.com
  - ENCRYPTION_LABEL=LDLRs9CbbM8G
  - AUTHOR_EMAIL=mika.br@gmail.com
  - ENCRYPTION_LABEL=eY8KCMPJAdPw
  - AUTHOR_EMAIL=mika.br@gmail.com
  - ENCRYPTION_LABEL=OQtxL3IB0v9j
after_success:
- chmod 755 .push_gh_pages.sh
- ./.push_gh_pages.sh

